fix: make rekor.pub a variable
sigstore/sigstore-js pull request #216
Opened 2022-12-20 23:24 UTC by laurentsimon

Signed-off-by: laurentsimon <laurentsimon@google.com>

closes https://github.com/sigstore/sigstore-js/issues/215

#### Summary
Te rekor.pub key is stored as a file. The file path does not resolve properly if the caller calls the API (vs CLI). When using [ncc](https://github.com/vercel/ncc), the file is not packaged with the final .js file. Using a variable solves these problems.

2022-12-21 10:19 UTC, feelepxyz commented on src/tlog/keys.ts
> +-----END PUBLIC KEY-----`
This file should in theory be relocated by `ncc` > [webpack-asset-relocator-loader](https://github.com/vercel/webpack-asset-relocator-loader) but I had a go at this and looks like it doesn't like the typescript compiled code here as it's trying to pattern match on `path.*` and TS generates this: `path_1.default.resolve`.

What does seem to work is changing this to use `require.resolve`:

```suggestion
  const pem = fs.readFileSync(
    require.resolve('../../store/rekor.pub'),
    'utf-8'
  );
```

2022-12-21 11:58 UTC, feelepxyz commented on src/tlog/keys.ts
>  import { createPublicKey, KeyObject } from 'crypto';
```suggestion
import { createPublicKey, KeyObject } from 'crypto';
import fs from 'fs';
```

2022-12-21 17:13 UTC, laurentsimon commented
Thanks @feelepxyz! I've accepted your changes.

2022-12-21 17:38 UTC, feelepxyz approved these changes
Appreciate the fix!

2022-12-22 01:41 UTC, bdehamer requested changes
I think the `rekor.pub` file needs to be added back in now.

2022-12-27 22:31 UTC, laurentsimon commented
I have added the rekor.pub file back in. PTAL

2023-01-03 16:42 UTC, feelepxyz approved these changes

2023-01-03 17:16 UTC, bdehamer approved these changes
👍

2023-01-03 17:16 UTC, merged